cc_library(
  name = "constants",
  srcs = ["constants.cc"],
  hdrs = ["constants.h"],
  visibility = ["//visibility:public"],
)

cc_library(
  name = "error",
  srcs = ["error.cc"],
  hdrs = ["error.h"],
)

cc_library(
  name = "frame",
  srcs = ["frame.cc"],
  hdrs = ["frame.h"],
)

cc_library(
  name = "settings",
  srcs = ["settings.cc"],
  hdrs = ["settings.h"],
  deps = [":error"],
)
